os: MinGW
shallow_clone: true

# create a build matrix to use various Lua and LuaJIT versions
environment:
  matrix:
    - LUAENV: luajit20
    - LUAENV: cinst

# cinst occasionally has problems, allow it to fail
# matrix:
#   allow_failures:
#     - LUAENV: cinst

# install required binaries via batch file (also sets %LUA% path)
install:
- cmd: .appveyor\install-lua.cmd

cache:
  - luajit20                    -> .appveyor\install-lua.cmd
  - 'C:\Program Files (x86)\Lua -> .appveyor\install-lua.cmd'

build: off

test_script:
- cmd: >-
    %LUA% test_get_os_name.lua
